// Select options for number of event people
export const numberOfPeople = [
    { label: 1 ,value: 1 },
    { label: 2 ,value: 2 },
    { label: 3 ,value: 3 },
    { label: 4 ,value: 4 },
    { label: 5 ,value: 5 },
    { label: 6 ,value: 6 },
    { label: 7 ,value: 7 },
    { label: 8 ,value: 8 },
    { label: 9 ,value: 9 }
];


// Select options for event location
// Need to fix
export const location = [
    { label: 'UTS' ,value: 'UTS' },
    { label: 'Alroy Park' ,value: 'Alroy Park' },
    { label: 'Auburn Basketball Courts' ,value: 'Auburn Basketball Courts' },
    { label: 'Aus Technology Park Court' ,value: 'Aus Technology Park Court' },
    { label: 'Balmain High School Courts' ,value: 'Balmain High School Courts' },
    { label: 'Bankstown Basketball Stadium' ,value: 'Bankstown Basketball Stadium' },
    { label: 'Broadway Outdoors' ,value: 'Broadway Outdoors' },
    { label: 'Camperdown Courts' ,value: 'Camperdown Courts' },
    { label: 'Cash Palace' ,value: 'Cash Palace' },
    { label: 'Chatswood Youth Centre' ,value: 'Chatswood Youth Centre' },
    { label: 'Claremont Street' ,value: 'Claremont Street' },
    { label: 'Cumberland Highway' ,value: 'Cumberland Highway' },
    { label: 'Darling Harbor Australia Rucker Park' ,value: 'Darling Harbor Australia Rucker Park' },
    { label: 'Elphinstone Road' ,value: 'Elphinstone Road' },
    { label: 'Emerton Leisure Centre' ,value: 'Emerton Leisure Centre' },
    { label: 'Erlestoke Park' ,value: 'Erlestoke Park' },
    { label: 'Everitt Crescent' ,value: 'Everitt Crescent' },
    { label: 'Fairfield Leisure Centre' ,value: 'Fairfield Leisure Centre' },
    { label: 'Five Dock Leisure Centre' ,value: 'Five Dock Leisure Centre' },
    { label: 'Freame Park' ,value: 'Freame Park' },
    { label: 'Glebe' ,value: 'Glebe' },
    { label: 'Glebe PCYC' ,value: 'Glebe PCYC' },
    { label: 'Haberfield Courts' ,value: 'Haberfield Courts' },
    { label: 'Hallstrom Park Courts' ,value: 'Hallstrom Park Courts' },
    { label: 'Harris Street' ,value: 'Harris Street' },
    { label: 'Hills Basketball Stadium' ,value: 'Hills Basketball Stadium' },
    { label: 'Homebush Road, Strathfield' ,value: 'Homebush Road, Strathfield' },
    { label: 'Jocelyn Half Court' ,value: 'Jocelyn Half Court' },
    { label: 'Kegworth Public School Reserve' ,value: 'Kegworth Public School Reserve' },
    { label: 'Kellyville' ,value: 'Kellyville' },
    { label: 'Kenneth Road' ,value: 'Kenneth Road' },
    { label: 'Kevin Betts Stadium' ,value: 'Kevin Betts Stadium' },
    { label: 'Lethbridge Park' ,value: 'Lethbridge Park' },
    { label: 'Liberty Grove Basketball Court' ,value: 'Liberty Grove Basketball Court' },
    { label: 'Loftus Square Park' ,value: 'Loftus Square Park' },
    { label: 'Lower Beach Street' ,value: 'Lower Beach Street' },
    { label: 'Luxford Gardens' ,value: 'Luxford Gardens' },
    { label: 'Macquarie Park (Optus)' ,value: 'Macquarie Park (Optus)' },
    { label: 'Marc Tiu and WarYU Home Court' ,value: 'Marc Tiu and WarYU Home Court' },
    { label: 'May Cowpe Reserve' ,value: 'May Cowpe Reserve' },
    { label: 'Maycowpe Reserve' ,value: 'Maycowpe Reserve' },
    { label: 'Merrylands Court' ,value: 'Merrylands Court' },
    { label: 'Meurants Lane' ,value: 'Meurants Lane' },
    { label: 'Michelll Reserve' ,value: 'Michelll Reserve' },
    { label: 'Midgee Reserve' ,value: 'Midgee Reserve' },
    { label: 'Moore Park' ,value: 'Moore Park' },
    { label: 'Nathaniel Park' ,value: 'Nathaniel Park' },
    { label: 'National Centre of Indigenous Excellence' ,value: 'National Centre of Indigenous Excellence' },
    { label: 'North Ryde RSL Courts' ,value: 'North Ryde RSL Courts' },
    { label: 'North Sydney Indoor Sports Centre' ,value: 'North Sydney Indoor Sports Centre' },
    { label: 'North Sydney TAFE' ,value: 'North Sydney TAFE' },
    { label: 'Nuffield Park' ,value: 'Nuffield Park' },
    { label: 'Park Street' ,value: 'Park Street' },
    { label: 'Paterson Courts' ,value: 'Paterson Courts' },
    { label: 'Paul Street' ,value: 'Paul Street' },
    { label: 'Pearce Reserve' ,value: 'Pearce Reserve' },
    { label: 'Penrith Basketball Stadium' ,value: 'Penrith Basketball Stadium' },
    { label: 'Perry Park Micro-Court' ,value: 'Perry Park Micro-Court' },
    { label: 'Phillip Cook' ,value: 'Phillip Cook' },
    { label: 'Piper Street' ,value: 'Piper Street' },
    { label: 'Prince Alfred Park' ,value: 'Prince Alfred Park' },
    { label: 'Railway St Court' ,value: 'Railway St Court' },
    { label: 'Ridgeview Park' ,value: 'Ridgeview Park' },
    { label: 'Rosebery Half Court' ,value: 'Rosebery Half Court' },
    { label: 'RSL Youth' ,value: 'RSL Youth' },
    { label: 'Sherwin Park' ,value: 'Sherwin Park' },
    { label: 'SJB Courts' ,value: 'SJB Courts' },
    { label: 'Stanhope Leisure Centre' ,value: 'Stanhope Leisure Centre' },
    { label: 'State Sports Centre' ,value: 'State Sports Centre' },
    { label: 'Sydney Boys High School' ,value: 'Sydney Boys High School' },
    { label: 'Sydney Harbour Bridge' ,value: 'Sydney Harbour Bridge' },
    { label: 'Sydney Superdome' ,value: 'Sydney Superdome' },
    { label: 'Sydney Uni Sports Centre' ,value: 'Sydney Uni Sports Centre' },
    { label: 'The Beat' ,value: 'The Beat' },
    { label: 'The Brickpit' ,value: 'The Brickpit' },
    { label: 'The Oval (full court)' ,value: 'The Oval (full court)' },
    { label: 'Tilden Street' ,value: 'Tilden Street' },
    { label: 'Treves Street' ,value: 'Treves Street' },
    { label: 'Waterloo Park' ,value: 'Waterloo Park' },
    { label: 'Whitlam Leaisure Centre' ,value: 'Whitlam Leaisure Centre' },
    { label: 'Other Place' ,value: 'Other Place' }
];



// Select options for have ball

export const ballStatus = [
    { label: 'Yes' ,value: true },
    { label: 'No' ,value: false }
];